### ISSUE TITLE
Wrong Type in Environment.php in 2.0.0-alpha1

### ISSUE THREAD

**Issue by kalzekdor** [ftrrtf/rollbar-notifier#5]
There appears to be a bug in [Environment.php](https://github.com/ftrrtf/rollbar-notifier/blob/2.0.0-alpha1/src/Environment.php) in the 2.0.0-alpha1 branch.

Here's the [constructor](https://github.com/ftrrtf/rollbar-notifier/blob/2.0.0-alpha1/src/Environment.php#L26):

```
public function __construct(array $options = array())
{
    $resolver = new OptionsResolver();
    $this->setDefaultOptions($resolver);
    $this->options = $resolver->resolve($options); 
}
```

Note that it's passing an object of type `Symfony\Component\OptionsResolver\OptionsResolver` to `setDefaultOptions`. Now, take a look at that method's [signature](https://github.com/ftrrtf/rollbar-notifier/blob/2.0.0-alpha1/src/Environment.php#L282):

`
protected function setDefaultOptions(Options $resolver)
`

It's expecting an object of type `Symfony\Component\OptionsResolver\Options`, causing the following error: `PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Ftrrtf\Rollbar\Environment::setDefaultOptions() must be an instance of Symfony\Component\OptionsResolver\Options, instance of Symfony\Component\OptionsResolver\OptionsResolver given`

**Comment by feamsr00** [comment]
:+1: ... am affected by this

**Comment by ftrrtf** [comment]
@kalzekdor Sorry for the delayed response, I will try to review and merge until the end of the week. Thank you for contributing.

**Comment by ftrrtf** [comment]
@kalzekdor Merged. Thanks!
