### ISSUE TITLE
Deprecated classes and methods Symfony 2.8

### ISSUE THREAD

**Issue by OxCom** [ftrrtf/rollbar-notifier#7]
Please, update Your code to avoid such notifications.

- Calling the Symfony\Component\OptionsResolver\OptionsResolver::setAllowedTypes method with an array of options is deprecated since version 2.6 and will be removed in 3.0
./vendor/ftrrtf/rollbar-notifier/src/Ftrrtf/Rollbar/Environment.php

v1.0.3
Thank You

**Comment by ftrrtf** [comment]
was updated in #2 already, just tagged the latest version (sorry for my late reply)
